const getCurrenciesScript = "(function() { "
    ""
    "var interestObj = new Object();"
    ""
    "var currenciesArea = document.getElementsByTagName('body')[0]"
    ".getElementsByTagName('header')[0]"
    ".getElementsByClassName('sub-nav')[0]"
    ".getElementsByClassName('container')[0]"
    ".getElementsByTagName('ul')[0];"
    ""
    "var liItems = Array.from(currenciesArea.getElementsByTagName('li'));"
    "interestObj.currencies = liItems.map(e => {"
    "var link = e.getElementsByTagName('a')[0];"
    "var linkObj = new Object();"
    "linkObj.url = link.getAttribute('href');"
    "linkObj.title = link.getAttribute('title');"
    "return linkObj;"
    "});"
    ""
// Serialize interest data
    "var jsonString= JSON.stringify(interestObj);"
    ""
    "return ('<html>'+jsonString+'</html>'); })();";
