const getExchangesScript = "(function() { "
    ""
    "var exchangesResultObj = new Object();"
    ""
    "var exchangeArea = document.getElementsByTagName('body')[0]"
    ".getElementsByTagName('main')[0]"
    ".getElementsByClassName('container')[0]"
    ".getElementsByClassName('row')[0]"
    ".getElementsByTagName('article')[0];"
    ""
    "var exchangeSections = exchangeArea.getElementsByTagName('section');"
    ""
    "exchangesResultObj.updatedTime = exchangeArea"
    ".getElementsByTagName('h1')[0]"
    ".getElementsByTagName('small')[0].innerText;"
    ""
    "exchangesResultObj.averageRate = exchangeSections[0].getElementsByClassName('form-group')[0]"
    ".getElementsByTagName('form')[0]"
    ".getElementsByClassName('row')[0]"
    ".getElementsByClassName('col-xs-12 col-sm-12 col-md-5 text-center')[1]"
    ".getElementsByClassName('form-group')[0]"
    ".getElementsByClassName('input-group')[0]"
    ".getElementsByTagName('input')[0].getAttribute('value');"
    ""
    "var rateRows = exchangeSections[1].getElementsByClassName('mw700')[0]"
    ".getElementsByClassName('table-responsive')[0]"
    ".getElementsByTagName('table')[0]"
    ".getElementsByTagName('tbody')[0]"
    ".getElementsByTagName('tr');"
    ""
    "exchangesResultObj.rates = Array.from(rateRows)"
    ".map(row => {"
    "var rateObj = new Object();"
    "var columns = row.getElementsByTagName('td');"
    "var bankInfo = columns[0].getElementsByTagName('a')[0];"
    "rateObj.bankName = bankInfo.getElementsByTagName('span')[1].innerText;"
    "rateObj.bankUrl = bankInfo.getAttribute('href');"
    "rateObj.buyCash = columns[1].getAttribute('data-int');"
    "rateObj.buyTransfer = columns[2].getAttribute('data-int');"
    "rateObj.sellCash = columns[3].getAttribute('data-int');"
    "rateObj.sellTransfer = columns[4].getAttribute('data-int');"
    "return rateObj;"
    "});"
    ""

// Serialize interest data
    "var jsonString= JSON.stringify(exchangesResultObj);"
    ""
    "return ('<html>'+jsonString+'</html>'); })();";
