const getGasolinePricesScript = "(function() { "
    ""
    "var gasPricesObj = new Object();"
    ""
    "var gasPriceArticle = document.getElementsByTagName('body')[0]"
    ".getElementsByTagName('main')[0]"
    ".getElementsByClassName('container')[0]"
    ".getElementsByClassName('row')[0]"
    ".getElementsByTagName('article')[0];"
    ""
    "gasPricesObj.updatedTime = gasPriceArticle.getElementsByTagName('h1')[0]"
    ".getElementsByTagName('small')[0].innerText;"
    ""
    "var gasPriceRows = gasPriceArticle.getElementsByClassName('table-responsive')[0]"
    ".getElementsByTagName('table')[0]"
    ".getElementsByTagName('tbody')[0]"
    ".getElementsByTagName('tr');"
    ""
    "gasPricesObj.domesticPrices = Array.from(gasPriceRows).map(row => {"
    "var gasPriceObj = new Object();"
    "var ths = row.getElementsByTagName('th');"
    "if (ths.length > 0) {"
    "gasPriceObj.sellerName = ths[0].getElementsByTagName('a')[0].innerText;"
    "var tds = row.getElementsByTagName('td');"
    "gasPriceObj.area1Price = tds[0].innerText;"
    "gasPriceObj.area2Price = tds[1].innerText;"
    "} else {"
    "gasPriceObj.sellerName = '';"
    "gasPriceObj.area1Price = '';"
    "gasPriceObj.area2Price = '';"
    "}"
    "return gasPriceObj;"
    "});"
    ""
    "var jsonString= JSON.stringify(gasPricesObj);"
    ""
    "return ('<html>'+jsonString+'</html>'); })();";
