const getGasolinePricesScript = "(function() { "
    ""
    "var gasPricesObj = new Object();"
    ""
    "var gasPriceArticle = document.getElementsByTagName('body')[0]"
    ".getElementsByTagName('main')[0]"
    ".getElementsByClassName('container')[0]"
    ".getElementsByClassName('row')[0]"
    ".getElementsByTagName('article')[0];"
    ""
    "gasPricesObj.updatedTime = gasPriceArticle.getElementsByTagName('h1')[0]"
    ".getElementsByTagName('small')[0].innerText;"
    ""
    "var gasPriceRows = gasPriceArticle.getElementsByClassName('table-responsive')[0]"
    ".getElementsByTagName('table')[0]"
    ".getElementsByTagName('tbody')[0]"
    ".getElementsByTagName('tr');"
    ""
    "gasPricesObj.domesticPrices = Array.from(gasPriceRows).map(row => {"
    "var gasPriceObj = new Object();"
    "var ths = Array.from(row.getElementsByTagName('th'));"
    "if (ths.length > 0) {"
    "gasPriceObj.sellerName = ths[0].getElementsByTagName('a')[0].innerText;"
    "if (!gasPriceObj.sellerName || gasPriceObj.sellerName === '') {"
    "gasPriceObj.sellerName = ths[0].getElementsByTagName('a')[0].textContent;"
    "}"
    "var tds = Array.from(row.getElementsByTagName('td'));"
    "gasPriceObj.area1Price = tds[0].innerText;"
    "if (!gasPriceObj.area1Price || gasPriceObj.area1Price === '') {"
    "gasPriceObj.area1Price = tds[0].textContent;"
    "}"
    "gasPriceObj.area2Price = tds[1].textContent;"
    "if (!gasPriceObj.area2Price || gasPriceObj.area2Price === '') {"
    "gasPriceObj.area2Price = tds[1].textContent;"
    "}"
    "} else {"
    "gasPriceObj.sellerName = '';"
    "gasPriceObj.area1Price = '';"
    "gasPriceObj.area2Price = '';"
    "}"
    "return gasPriceObj;"
    "});"
    ""
    "var jsonString= JSON.stringify(gasPricesObj);"
    ""
    "return ('<html>'+jsonString+'</html>'); })();";
