const getGoldPricesScript = "(function() { "
    ""
    "var goldPricesObj = new Object();"
    ""
    "var goldPricesArticle = document.getElementsByTagName('body')[0]"
    ".getElementsByTagName('main')[0]"
    ".getElementsByClassName('container')[0]"
    ".getElementsByClassName('row')[0];"
    ""
    "var goldPricesRows = goldPricesArticle.getElementsByTagName('article')[0]"
    ".getElementsByTagName('table')[0]"
    ".getElementsByTagName('tbody')[0]"
    ".getElementsByTagName('tr');"
    ""
    "var lastAreaName = 'Unknown area';"
    "goldPricesObj.domesticPrices = Array.from(goldPricesRows).map(row => {"
    "var priceObj = new Object();"
    "var thItems = row.getElementsByTagName('th');"
    "if (thItems.length > 0) {"
    "lastAreaName = thItems[0].innerText;"
    "priceObj.areaName = lastAreaName"
    "} else {"
    "priceObj.areaName = lastAreaName;"
    "}"
    "var tdItems = row.getElementsByTagName('td');"
    "var links = tdItems[0].getElementsByTagName('a');"
    "if (links.length > 0) {"
    "priceObj.seller = links[0].getElementsByTagName('strong')[0].innerText;"
    "priceObj.sellerUrl = links[0].getAttribute('href');"
    "priceObj.buyingPrice = tdItems[1].innerText;"
    "priceObj.sellingPrice = tdItems[2].innerText;"
    "} else {"
    "priceObj.seller = 'Unknown seller';"
    "priceObj.sellerUrl = 'Unknown link';"
    "}"
    "return priceObj;"
    "});"
    ""
    "var globalGoldPricesRows = goldPricesArticle"
    ".getElementsByTagName('aside')[0]"
    ".getElementsByTagName('div')[0]"
    ".getElementsByClassName('box')[0]"
    ".getElementsByClassName('box-content')[0]"
    ".getElementsByTagName('table')[0]"
    ".getElementsByTagName('tbody')[0]"
    ".getElementsByTagName('tr')[0]"
    ".getElementsByTagName('td');"
    ""
    "var globalPricePObj = new Object();"
    "globalPricePObj.price = globalGoldPricesRows[0].textContent;"
    "globalPricePObj.priceChange = globalGoldPricesRows[1].textContent;"
    "globalPricePObj.priceChangePercent = globalGoldPricesRows[2].textContent;"
    ""
    "goldPricesObj.globalPrice = globalPricePObj;"
    ""
    "var jsonString= JSON.stringify(goldPricesObj);"
    ""
    "return ('<html>'+jsonString+'</html>'); })();";
